services:

  app:
    image: bitnami/laravel:10.3.3
    container_name: 2child-back-auth-app
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - 2child-back-auth-net
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql
    container_name: 2child-back-auth-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - 2child-back-auth-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  2child-back-auth-net:
    driver: 'bridge'

volumes:
  db-data:
    external: true